using UnityEngine;
using TMPro;
using UnityEngine.UI;

namespace DayGameplayScripts
{
    public class GuestTicketUI : MonoBehaviour
    {
        public Image portraitImage;
        public TextMeshProUGUI nameText;
        public TextMeshProUGUI lastNameText;
        public TextMeshProUGUI ageText;
        public TextMeshProUGUI genderText;
        public TextMeshProUGUI dateText;

        private TicketData _ticket;

        private RectTransform _rectTransform;
        private Vector2 _initialPosition;
        private bool _initialized;

        private void OnEnable()
        {
            if (_initialized) return;

            _rectTransform = GetComponent<RectTransform>();
            _initialPosition = _rectTransform.anchoredPosition;
            _initialized = true;
        }

        public void Show(TicketData ticket)
        {
            AudioManager.Instance.PlaySFX("ticketOpenMusic");
            if (ticket == null)
            {
                Debug.LogError("GuestTicketUI.Show: ticket == null");
                return;
            }

            _ticket = ticket;

            // üîÅ –≤—Å–µ–≥–¥–∞ –≤–æ–∑–≤—Ä–∞—â–∞–µ–º –±–∏–ª–µ—Ç –≤ –∏—Å—Ö–æ–¥–Ω–æ–µ –º–µ—Å—Ç–æ
            if (_rectTransform != null)
                _rectTransform.anchoredPosition = _initialPosition;

            gameObject.SetActive(true);

            nameText.text = $"–ò: {_ticket.firstName}";
            lastNameText.text = $"–§: {_ticket.lastName}";
            ageText.text = $"–í–æ–∑—Ä–∞—Å—Ç: {_ticket.age}";
            genderText.text = $"–ü–æ–ª: {_ticket.gender}";
            dateText.text = $"–î–µ–π—Å—Ç–≤–∏—Ç–µ–ª–µ–Ω –¥–æ: {_ticket.validUntil}";

            if (portraitImage && _ticket.portrait != null)
                portraitImage.sprite = _ticket.portrait;
        }

        public void Hide()
        {
            AudioManager.Instance.PlaySFX("menuButtonMusic");
            gameObject.SetActive(false);
        }
    }
}